AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    AWS Serverless Application

    Sample SAM Template for AWS Serverless Application

Globals:
    Function:
        Timeout: 30
        Environment:
          Variables:
            USER_TABLE: UsersTable
            AUTH_TABLE: AuthsTable

Resources:
    CreateUserFunction:
      Type: AWS::Serverless::Function 
      Properties:
        CodeUri: .
        Handler: create_user.lambda_handler
        Runtime: python3.7
        Events:
          Createuser:
            Type: Api 
            Properties:
              Path: /users/{userid}
              Method: put

    GetUserFunction:
      Type: AWS::Serverless::Function 
      Properties:
        CodeUri: .
        Handler: get_user.lambda_handler
        Runtime: python3.7
        Events:
          Createuser:
            Type: Api 
            Properties:
              Path: /users/{userid}
              Method: get

    AddCourseFunction:
      Type: AWS::Serverless::Function 
      Properties:
        CodeUri: .
        Handler: add_course.lambda_handler
        Runtime: python3.7
        Events:
          Createuser:
            Type: Api 
            Properties:
              Path: /users/{userid}/{courseid}
              Method: put

    CreateCourseFunction:
      Type: AWS::Serverless::Function 
      Properties:
        CodeUri: .
        Handler: create_course.lambda_handler
        Runtime: python3.7
        Events:
          Createuser:
            Type: Api 
            Properties:
              Path: /courses/{courseid}
              Method: put

    GetCourseFunction:
      Type: AWS::Serverless::Function 
      Properties:
        CodeUri: .
        Handler: get_course.lambda_handler
        Runtime: python3.7
        Events:
          Createuser:
            Type: Api 
            Properties:
              Path: /courses/{courseid}
              Method: get
