AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    AWS Serverless Application

    Sample SAM Template for AWS Serverless Application

Globals:
    Function:
        Timeout: 30
        Environment:
          Variables:
            USER_TABLE: UsersTable
            S3_BUCKET: !Ref ColibriUserSinkBucket

Resources:
  ColibriUserSinkBucket:
    Type: 'AWS::S3::Bucket'

  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: UsersTable
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
      StreamSpecification:
        StreamViewType: NEW_IMAGE

  DynamoStreamProcessorFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: .
      Handler: process_stream.lambda_handler
      Runtime: python3.7
      Policies:
        - S3CrudPolicy:
            BucketName:
              !Ref ColibriUserSinkBucket
      Events:
        DynamoDB1:
          Type: DynamoDB
          Properties:
            Stream:
              'Fn::GetAtt':
                - UsersTable
                - StreamArn
            StartingPosition: TRIM_HORIZON
            BatchSize: 100
  

  CreateUserFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: .
      Handler: create_user.lambda_handler
      Runtime: python3.7
      Policies:
        - DynamoDBCrudPolicy:
            TableName:
              !Ref UsersTable
      Events:
        Createuser:
          Type: Api 
          Properties:
            Path: /users
            Method: put
